CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    completed_date TIMESTAMP NULL,
    completed BOOLEAN DEFAULT FALSE 
);
